/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DecimalFloatingPointExample;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAMain() {
        App.main(null);        
    }
}
